---
- name: Use /dev/urandom for Java
  replace:
    dest: /usr/lib/jvm/jre/lib/security/java.security
    regexp: '^securerandom.source.*'
    replace: 'securerandom.source=file:/dev/./urandom'
  become: yes

- name: Copy keycloak service
  template:
    src: keycloak.service.j2
    dest: /etc/systemd/system/keycloak.service
    owner: root
    group: root
  become: yes
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version >= "7"
  notify:
    - Reload systemd

- name: Enable keycloak service
  service:
    name: keycloak
    enabled: yes
  become: yes
